name: Scrape urls and upload to s3

on: workflow_dispatch

jobs:
    scrape:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Install uv
              uses: astral-sh/setup-uv@v5

            - name: "Set up Python"
              uses: actions/setup-python@v5
              with:
                python-version-file: ".python-version"

            - name: Install the project
              run: uv sync --locked --all-extras --dev

            - name: Run Scraper
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
                AUCTIONS_BUCKET: ${{ secrets.AUCTIONS_BUCKET }}
              run: uv run src/main.py
                    

